font:
  # iNSTA
  normal:
   family: FiraCode Nerd Font
   style:  Semibold
  
  italic:
   family: FiraCode Nerd Font
   style:  Italic
  
  bold_italic:
   family: FiraCode Nerd Font
   style:  Bold Italic
  
  size: 11

# Uncomment for tomorrow night base16 theme
# colors:
#   # Default colors
#   primary:
#     background: '0x1d1f21'
#     foreground: '0xc5c8c6'

#   # Normal colors
#   normal:
#     black:   '0x1d1f21'
#     red:     '0xcc6666'
#     green:   '0xb5bd68'
#     yellow:  '0xf0c674'
#     blue:    '0x81a2be'
#     magenta: '0xb294bb'
#     cyan:    '0x8abeb7'
#     white:   '0xc5c8c6'

#   # Bright colors
#   bright:
#     black:   '0x969896'
#     red:     '0xcc6666'
#     green:   '0xb5bd68'
#     yellow:  '0xf0c674'
#     blue:    '0x81a2be'
#     magenta: '0xb294bb'
#     cyan:    '0x8abeb7'
#     white:   '0xffffff'

# Uncomment for one dark theme
colors:
  # Default colors
  primary:
    background: '0x1e2127'
    foreground: '0xabb2bf'

    # Bright and dim foreground colors
    #
    # The dimmed foreground color is calculated automatically if it is not present.
    # If the bright foreground color is not set, or `draw_bold_text_with_bright_colors`
    # is `false`, the normal foreground color will be used.
    #dim_foreground: '0x9a9a9a'
    bright_foreground: '0xe6efff'

  # Cursor colors
  #
  # Colors which should be used to draw the terminal cursor. If these are unset,
  # the cursor color will be the inverse of the cell color.
  #cursor:
  #  text: '0x000000'
  #  cursor: '0xffffff'

  # Normal colors
  normal:
    black:   '0x1e2127'
    red:     '0xe06c75'
    green:   '0x98c379'
    yellow:  '0xd19a66'
    blue:    '0x61afef'
    magenta: '0xc678dd'
    cyan:    '0x56b6c2'
    white:   '0x828791'

  # Bright colors
  bright:
    black:   '0x5c6370'
    red:     '0xe06c75'
    green:   '0x98c379'
    yellow:  '0xd19a66'
    blue:    '0x61afef'
    magenta: '0xc678dd'
    cyan:    '0x56b6c2'
    white:   '0xe6efff'

  # Dim colors
  #
  # If the dim colors are not set, they will be calculated automatically based
  # on the `normal` colors.
  dim:
    black:   '0x1e2127'
    red:     '0xe06c75'
    green:   '0x98c379'
    yellow:  '0xd19a66'
    blue:    '0x61afef'
    magenta: '0xc678dd'
    cyan:    '0x56b6c2'
    white:   '0x828791'

  # Indexed Colors
  #
  # The indexed colors include all colors from 16 to 256.
  # When these are not set, they're filled with sensible defaults.
  #indexed_colors:
  #  - { index: 16, color: '0x000000' }
